import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

class LocalizationService extends ChangeNotifier {
  static final LocalizationService _instance = LocalizationService._internal();

  static LocalizationService get instance => _instance;

  LocalizationService._internal();

  // 'si' for Sinhala, 'en' for English
  String _currentLocale = 'si';
  bool _hasSetLanguage = false;

  String get currentLocale => _currentLocale;
  bool get hasSetLanguage => _hasSetLanguage;

  static const String _localeKeyParent = 'sipsara_language_code';
  static const String _localeKeyTherapist = 'sipsara_language_code_therapist';
  static const String _hasSetLanguageKey = 'sipsara_has_set_language';
  
  String _currentRole = 'parent';

  Future<void> init() async {
    final prefs = await SharedPreferences.getInstance();
    _currentRole = prefs.getString('cached_user_role') ?? 'parent';
    await loadForRole(_currentRole);
  }

  Future<void> loadForRole(String role) async {
    _currentRole = role;
    final prefs = await SharedPreferences.getInstance();
    
    String key = role == 'therapist' ? _localeKeyTherapist : _localeKeyParent;
    String defaultLocale = role == 'therapist' ? 'en' : 'si';
    
    _currentLocale = prefs.getString(key) ?? defaultLocale;
    _hasSetLanguage = prefs.getBool(_hasSetLanguageKey) ?? false;
    notifyListeners();
  }

  Future<void> setLocale(String localeCode) async {
    if (_currentLocale == localeCode) return;
    _currentLocale = localeCode;
    
    // Once they explicitly change the language, mark it as set
    _hasSetLanguage = true;
    
    final prefs = await SharedPreferences.getInstance();
    String key = _currentRole == 'therapist' ? _localeKeyTherapist : _localeKeyParent;
    
    await prefs.setString(key, _currentLocale);
    await prefs.setBool(_hasSetLanguageKey, true);
    
    notifyListeners();
  }
  
  Future<void> markLanguageAsSet() async {
    if (_hasSetLanguage) return;
    _hasSetLanguage = true;
    final prefs = await SharedPreferences.getInstance();
    await prefs.setBool(_hasSetLanguageKey, true);
    notifyListeners();
  }

  String t(String key) {
    return _translations[_currentLocale]?[key] ?? _translations['en']?[key] ?? key;
  }

  static const Map<String, Map<String, String>> _translations = {
    'si': {
      'welcome_title': 'ආයුබෝවන්!',
      'welcome_subtitle': 'ඔබගේ සිංහල ඉගෙනුම්\nවික්‍රමය මෙතැනින් අරඹන්න!',
      'welcome_btn_signup': 'ආරම්භ කරන්න',
      'welcome_btn_signin': 'මට දැනටමත් ගිණුමක් ඇත',
      'btn_signin': 'ඇතුළු වන්න',
      'signing_in': 'ඇතුළු වෙමින්...',
      'btn_signup': 'ලියාපදිංචි වන්න',
      'email': 'විද්‍යුත් තැපෑල',
      'email_hint': 'විද්‍යුත් තැපැල් ලිපිනය',
      'password': 'මුරපදය',
      'password_hint': 'ඔබගේ මුරපදය',
      'password_hint_create': 'මුරපදයක් සාදන්න',
      'forgot_password': 'මුරපදය අමතකද?',
      'forgot_password_desc': 'කණගාටු නොවන්න! ඔබගේ විද්‍යුත් තැපැල් ලිපිනය ඇතුලත් කරන්න. මුරපදය නැවත සැකසීමට අපි පින් අංකයක් එවන්නෙමු.',
      'sending_code': 'කේතය යවමින් පවතී...',
      'send_code': 'කේතය යවන්න',
      'check_email': 'ඔබගේ විද්‍යුත් තැපෑල පරීක්ෂා කරන්න',
      'otp_sent_to': 'අපි අංක 6 කින් යුත් කේතයක් යවා ඇත\n',
      'otp_enter_below': '.\nඔබගේ ගිණුම තහවුරු කිරීමට එය පහතින් ඇතුලත් කරන්න.',
      'resend_code_in': 'තත්පර {time} කින් නැවත එවන්න',
      'resend_otp_now': 'දැන් නැවත කේතය යවන්න',
      'verify_code': 'කේතය තහවුරු කරන්න',
      'dont_have_account': 'ඔබට ගිණුමක් නොමැතිද? ',
      'already_have_account': 'ඔබට දැනටමත් ගිණුමක් තිබේද? ',
      'signin_title': 'නැවතත් සාදරයෙන් පිළිගනිමු!',
      'signin_subtitle': 'ඔබගේ ඉගෙනුම් වික්‍රමය ආරම්භ කිරීමට ඇතුළු වන්න',
      'signup_title': 'ඔබගේ ගිණුම සාදන්න',
      'signup_subtitle': 'අදම ඔබගේ ඉගෙනුම් වික්‍රමයට එක්වන්න',
      'parent_name': 'දෙමාපියන්ගේ නම',
      'parent_name_hint': 'ඔබගේ නම',
      'role_parent': 'දෙමාපිය',
      'role_therapist': 'චිකිත්සක',
      'specialization_hint': 'විශේෂඥතාව (කථන චිකිත්සක)',
      'clinic_hint': 'සායනයේ නම (විකල්ප)',
      'or': 'හෝ',
      'mobile_number': 'දුරකථන අංකය',
      'mobile_number_hint': 'ඔබගේ දුරකථන අංකය',
      'confirm_password': 'මුරපදය තහවුරු කරන්න',
      'confirm_password_hint': 'මුරපදය නැවත ඇතුලත් කරන්න',
      'agree_terms': 'සිප්සර භාවිතා කිරීමේ නියමයන්ට හා රහස්‍යතා ප්‍රතිපත්තියට එකඟ වෙමි.',
      'benefit_private': 'පෞද්ගලික',
      'start_assessment': 'ඇගයීම ආරම්භ කරන්න',
      'maybe_later': 'පසුව බලමු',
      'assessment_later_desc': 'ඔබට මෙය සිසුවාගේ ගිණුමෙන් ඕනෑම වේලාවක ආරම්භ කළ හැක.',
      'start_from_profile': 'ඔබට මෙය සිසුවාගේ ගිණුමෙන් පසුව ආරම්භ කළ හැක.',
      'language': 'භාෂාව',
      'select_language': 'භාෂාව තෝරන්න',
      'settings': 'සැකසීම',
      'field_required': 'මෙම තොරතුර අනිවාර්යයි',
      'invalid_email': 'වලංගු ඊමේල් ලිපිනයක් ඇතුලත් කරන්න',
      'invalid_phone': 'වලංගු දුරකථන අංකයක් ඇතුලත් කරන්න',
      'password_short': 'මුරපදය අවම වශයෙන් අකුරු 6 කින් යුක්ත විය යුතුය',
      'passwords_dont_match': 'මුරපද සමාන නොවේ',
      'must_agree_terms': 'ඔබ නියමයන්ට හා රහස්‍යතා ප්‍රතිපත්තියට එකඟ විය යුතුය',
      'or_continue_with': 'නැතහොත් මේ සමඟ දිගටම යන්න',
      'error_occurred': 'දෝෂයක් ඇතිවිය. කරුණාකර නැවත උත්සාහ කරන්න.',
      'change': 'වෙනස් කරන්න',
      'parent_account': 'දෙමාපිය ගිණුම',
      'account_security': 'ගිණුම සහ ආරක්ෂාව',
      'full_name': 'සම්පූර්ණ නම',
      'delete_account': 'ගිණුම මකා දමන්න',
      'my_students': 'මගේ සිසුන්',
      'subscription': 'ගෙවීම් සහ දායකත්ව',
      'coming_soon': 'ළඟදීම',
      'notifications': 'නිවේදන',
      'help_support': 'උදව් සහ සහාය',
      'edit': 'වෙනස් කරන්න',
      'parent_hub': 'දෙමාපිය අංශය',
      'hello_parent': 'ආයුබෝවන්',
      'children': 'දරුවන්',
      'this_week': 'මේ සතියේ',
      'connected': 'සම්බන්ධතා',
      'reports': 'වාර්තා',
      'messages': 'පණිවිඩ',
      'therapists': 'චිකිත්සකයින්',
      'your_children': 'ඔබේ දරුවන්',
      'select_a_child': 'සිසුවෙකු තෝරන්න',
      'recent_activity': 'මෑත ක්‍රියාකාරකම්',
      'last_played': 'අවසන් වරට ක්‍රීඩා කළේ',
      'skills_mastered': 'කුසලතා ප්‍රගතිය',
      'no_students_yet': 'තවමත් සිසුන් නැත',
      'view_all_students': 'සිසුන් දෙනාම බලන්න →',
      'show_less': 'අඩුවෙන් පෙන්වන්න',
      'student_added': 'සිසුවා එකතු කරන ලදී!',
      'student_setup_ready_1': ' සියල්ල සකසා ඇති අතර ඉගෙනීමට සූදානම්.',
      'personalize_learning': 'සිසුවට ගැළපෙන ඉගෙනීම',
      'evaluation_desc_1': 'විනාඩි 2ක කෙටි ඇගයීමක් මගින් ',
      'evaluation_desc_2': 'ගේ සුවිශේෂී ඉගෙනුම් රටාව තේරුම් ගෙන ඔවුන්ට ගැලපෙන ක්‍රියාකාරකම් සකස් කිරීමට අපට උපකාරී වේ.',
      'personalized': 'සිසුවට ගැළපෙන පාඩම්',
      '2_min': 'විනාඩි 2යි',
      'private': 'පෞද්ගලිකයි',
      'assessment_prompt_desc': 'විනාඩි 2ක කෙටි ඇගයීමක් මගින් ඔවුන්ගේ සුවිශේෂී ඉගෙනුම් රටාව තේරුම් ගෙන ඔවුන්ට ගැලපෙන ක්‍රියාකාරකම් සකස් කිරීමට අපට උපකාරී වේ.',
      'add_student': 'සිසුවෙකු එකතු කරන්න',
      'pending': 'නිම කරන්න',
      'completed': 'සම්පූර්ණයි',
      'premium_coming_soon': 'විශේෂිත පහසුකම් ළඟදීම!',
      'premium_desc': 'ඔබගේ දරුවාගේ ඉගෙනුම් අත්දැකීම තවත් උසස් මට්ටමකට ගෙන ඒම සඳහා නවතම විශේෂාංග රැසක් හඳුන්වා දීමට අප සූදානම්.',
      'login_alerts': 'පිවිසුම් ඇඟවීම්',
      'login_alerts_desc': 'ඔබගේ ගිණුමට නව උපාංගයකින් පිවිසෙන විට දැනුම් දෙන්න.',
      'learning_progress': 'ඉගෙනුම් ප්‍රගතිය',
      'learning_progress_desc': 'ඔබේ දරුවා පරීක්ෂණයක් හෝ සන්ධිස්ථානයක් සම්පූර්ණ කළ විට දැනුම් දෙන්න.',
      'app_updates': 'යෙදුම් යාවත්කාලීන සහ විශේෂාංග',
      'app_updates_desc': 'නව අධ්‍යාපනික මෙවලම් පිළිබඳ වැදගත් නිවේදන ලබා ගන්න.',
      'email_support': 'විද්‍යුත් තැපැල් සහාය',
      'phone_support': 'දුරකථන සහාය',
      'faq': 'නිතර අසන ප්‍රශ්න',
      'logout': 'ඉවත් වන්න',
      'activities': 'ක්‍රියාකාරකම්',
      'accuracy': 'නිරවද්‍යතාව',
      'day_streak': 'අඛණ්ඩව ඉගෙනගත් දින',
      'stars_earned': 'ලබාගත් තරු',
      'weekly_activity': 'සතිපතා ක්‍රියාකාරකම්',
      'recent_skills': 'මෑත කුසලතා',
      'view_advanced_reports': 'වැඩිදුර ප්‍රගති වාර්තා සහ සිතියම් බලන්න',
      'progress_report': 'ප්‍රගති වාර්තාව',
      'no_activities_played': 'තවමත් ක්‍රියාකාරකම් කර නැත',
      'whos_learning_today': 'අද ඉගෙන ගන්නේ කවුද?',
      'ready': 'සූදානම්',
      
      // Parent Hub Additions
      'last_active_prefix': 'අවසන් වරට ක්‍රියාකාරී වූයේ: ',
      'view_progress_btn': 'ප්‍රගතිය බලන්න →',
      'never': 'කිසිදාක නැත',
      'recent': 'මෑතකදී',
      'add_student_first_msg': 'ප්‍රගතිය බැලීමට පළමුව සිසුවෙකු ඇතුළත් කරන්න',
      'add_student_settings_hint': 'පළමු සිසුවා ඇතුළත් කිරීමට විකල්ප වෙත යන්න',
      
      'delete_account_desc': 'මෙම ක්‍රියාව ආපසු හැරවිය නොහැක. ඔබගේ සියලුම දත්ත සහ සිසුන්ගේ ගිණුම් ස්ථිරවම මකා දැමෙනු ඇත.',
      'delete_account_confirm': 'තහවුරු කිරීමට, ඔබගේ සම්පූර්ණ නම ඇතුළත් කරන්න:',
      'cancel': 'අවලංගු කරන්න',
      'password_changed': 'මුරපදය වෙනස් කර ඇත!',
      'update_password': 'මුරපදය යාවත්කාලීන කරන්න',
      'update_name': 'නම යාවත්කාලීන කරන්න',
      'update_name_desc': 'ඔබගේ ගිණුම යාවත්කාලීන කිරීමට ඔබගේ සම්පූර්ණ නම ඇතුළත් කරන්න.',
      'save_changes': 'වෙනස්කම් සුරකින්න',
      'name_updated_success': 'නම සාර්ථකව යාවත්කාලීන කරන ලදී!',
      'update_email_title': 'විද්‍යුත් තැපෑල යාවත්කාලීන කරන්න',
      'update_email_desc': 'නව විද්‍යුත් තැපැල් ලිපිනයක් ඇතුළත් කරන්න. තහවුරු කිරීමට අපි සත්‍යාපන කේතයක් එවන්නෙමු.',
      'send_verification_code': 'සත්‍යාපන කේතය යවන්න',
      'verify_email': 'විද්‍යුත් තැපෑල සත්‍යාපනය කරන්න',
      'verify_email_desc': 'අපි අංක 6 ක සත්‍යාපන කේතයක් යැව්වෙමු ',

      'verify_and_update': 'සත්‍යාපනය කර යාවත්කාලීන කරන්න',
      'email_updated_success': 'විද්‍යුත් තැපෑල සාර්ථකව යාවත්කාලීන කරන ලදී!',
      'change_password_title': 'මුරපදය වෙනස් කරන්න',
      'change_password_desc': 'ශක්තිමත් නව මුරපදයකින් ඔබගේ ගිණුම ආරක්ෂා කරන්න.',
      'delete': 'මකා දමන්න',
      'delete_permanently': 'ස්ථිරවම මකා දමන්න',
      'reset_skills_title': 'කුසලතා ප්‍රගතිය නැවත සකසන්නද?',
      'reset_skills_desc_prefix': '',
      'reset_skills_desc_suffix': ' ගේ සියලුම කුසලතා ප්‍රගතිය නැවත සැකසීමට ඔබට අවශ්‍යද? සම්පූර්ණ කරන ලද ක්‍රියාකාරකම්, ලකුණු, සහ අගුළු හරින ලද මට්ටම් නැවත ආරම්භයට සකසනු ඇත.',
      'reset_skills_success': ' ගේ කුසලතා ප්‍රගතිය නැවත සකසන ලදී!',
      'reset_skills_btn': 'නැවත සකසන්න',
      'delete_student_title': 'සිසුවා මකා දමන්නද?',
      'delete_student_desc_prefix': '',
      'delete_student_desc_suffix': ' ස්ථිරවම මකා දැමීමට ඔබට අවශ්‍ය බව නිසැකද? මෙම ක්‍රියාව ආපසු හැරවිය නොහැකි අතර ඉගෙනුම් ප්‍රගතිය ස්ථිරවම මැකී යනු ඇත.',
      'delete_student_therapist_warning': 'මෙම සිසුවා චිකිත්සකයෙකු සමඟ සම්බන්ධ වී ඇත. සිසුවා මකා දැමීමෙන් එම සම්බන්ධතාවය ස්ථිරවම බිඳ වැටෙනු ඇත.',
      'delete_student_success': ' සාර්ථකව මකා දමන ලදී.',

      'add_student_subtitle': 'ආරම්භ කිරීමට සිසුවෙකු එකතු කරන්න',
      'assessment_profile': 'ඇගයීම් ගිණුම',
      'select_area_evaluate': 'ඇගයීමට සුදුසු අංශයක් තෝරන්න',
      'cat_basic': 'මූලික ඩිස්ලෙක්සියා පරීක්ෂණය',
      'cat_reading': 'කියවීම හා දෘශ්‍ය සංජානන අපහසුතා',
      'cat_writing': 'ලිවීම සම්බන්ධ අපහසුතා',
      'cat_other': 'වෙනත් අපහසුතා',
      'btn_yes': 'ඔව්',
      'btn_no': 'නැත',
      'question_prefix': 'ප්‍රශ්නය ',
      'btn_finish_evaluation': 'ඇගයීම අවසන් කරන්න',

      // Add/Edit Student
      'add_student_desc': 'අමතර දරුවෙකු නොමිලේ එකතු කරන්න. ඔබගේ ගිණුමට දරුවන් 5 දෙනෙකු දක්වා එකතු කළ හැක.',
      'choose_avatar': 'ගිණුම සඳහා පින්තූරයක් තෝරන්න',
      'fantasy': 'ෆැන්ටසි',
      'kids': 'ළමයි',
      'student_first_name_hint': 'දරුවාගේ මුල් නම',
      'student_last_name_hint': 'දරුවාගේ අවසන් නම',
      'required_field': 'අවශ්‍යයි',
      'grade_1': '1 ශ්‍රේණිය',
      'auto_set': 'ස්වයංක්‍රීය',
      'daily_limit_prefix': 'දෛනික සීමාව: ',
      'student_updated_success': 'සිසුවා සාර්ථකව යාවත්කාලීන කෙරිණි!',
      'grade_set_info': 'ශ්‍රේණිය 1 ශ්‍රේණිය ලෙස සකසා ඇත',

      'update_changes': 'යාවත්කාලීන කරන්න',
      'edit_student': 'සිසුවා සංස්කරණය කරන්න',
      'no_limit': 'සීමාවක් නොමැත',
      'minutes': 'මිනිත්තු',
      'hours': 'පැය',
      'hour': 'පැය',

      // Consent Screen
      'parental_consent': 'දෙමාපිය කැමැත්ත',
      'student_protection_agreement': 'සිසු ආරක්ෂණ ගිවිසුම',
      'consent_review_terms': 'ඉදිරියට යාමට පෙර කරුණාකර පහත නියමයන් කියවා එකඟ වන්න.',
      'consent_items': 'කැමැත්ත ලබාදිය යුතු කරුණු',
      'guardian_confirmation_title': 'භාරකරු තහවුරු කිරීම',
      'guardian_confirmation_desc': 'මා මෙම දරුවාගේ දෙමාපියන් හෝ නීත්‍යානුකූල භාරකරු බවත්, ඔවුන් වෙනුවෙන් කැමැත්ත ලබා දීමට මට බලය ඇති බවත් මම තහවුරු කරමි.',
      'data_collection_title': 'ඉගෙනුම් දත්ත එකතු කිරීම',
      'data_collection_desc': 'මාගේ දරුවාගේ අධ්‍යාපනික අත්දැකීම් ඔවුන්ට ගැලපෙන අයුරින් සැකසීමට ඔවුන්ගේ ඉගෙනුම් දත්ත (ප්‍රතිචාර, ප්‍රගතිය සහ කාර්යසාධනය) එකතු කිරීම සහ සැකසීම සඳහා මම කැමැත්ත ප්‍රකාශ කරමි.',
      'screening_purpose_title': 'ඩිස්ලෙක්සියා පරීක්ෂාවේ අරමුණ',
      'screening_purpose_desc': 'මෙම යෙදුම 1 ශ්‍රේණියේ ඩිස්ලෙක්සියා පරීක්ෂාව සහ ඉගෙනුම් සහාය සඳහා නිර්මාණය කර ඇති බව මම තේරුම් ගනිමි. එය වෛද්‍ය රෝග විනිශ්චය ලබා නොදෙන අතර වෘත්තීය මාර්ගෝපදේශනය සමඟ භාවිතා කළ යුතුය.',
      'terms_privacy_title': 'භාවිත නියමයන් සහ රහස්‍යතා ප්‍රතිපත්තිය',
      'terms_privacy_desc': 'මා භාවිත නියමයන් සහ රහස්‍යතා ප්‍රතිපත්තිය කියවා ඊට එකඟ වී ඇත. මාගේ දරුවාගේ දත්ත ආරක්ෂිතව ගබඩා කරනු ඇති අතර තෙවන පාර්ශවයන් සමඟ බෙදා නොගන්නා බව මම තේරුම් ගනිමි.',
      'digital_signature': 'ඩිජිටල් අත්සන',
      'digital_signature_desc': 'ඔබගේ ඩිජිටල් අත්සන ලෙස ඔබගේ සම්පූර්ණ නම පහතින් ටයිප් කරන්න.',
      'signature_hint': 'දෙමාපියන්ගේ / භාරකරුගේ සම්පූර්ණ නම',
      'date_prefix': 'දිනය: ',
      'agree_continue': 'මම එකඟ වී ඉදිරියට යමි',
      
      // New Parent Hub Inner Screens Additions
      'skill_analytics': 'කුසලතා විශ්ලේෂණය',
      'phonological_awareness': 'ශබ්ද විද්‍යාත්මක අවබෝධය',
      'visual_discrimination': 'දෘශ්‍ය වෙනස්කම් හඳුනාගැනීම',
      'memory': 'මතකය',
      'letter_knowledge': 'අකුරු පිළිබඳ දැනුම',
      'tracing': 'අකුරු ලිවීම',
      'visual_hidden_search': 'සැඟවුණු පින්තූර සෙවීම',
      'visual_pattern_adventure': 'රටා ගැලපීම',
      'visual_sorting_adventure': 'හැඩතල වෙන් කිරීම',
      'visual_odd_one_out': 'වෙනස් එක තෝරන්න',
      'visual_memory_hats': 'මතක තොප්පි',
      'visual_picture_matching': 'පින්තූර ගැලපීම',
      'visual_connect_pairs': 'යුගල සම්බන්ධ කිරීම',
      'visual_shadow_matching': 'සෙවනැලි ගැලපීම',
      'visual_tangled_paths': 'පැටලුණු මාර්ග',
      'visual_position_concepts': 'ස්ථාන සංකල්ප',
      'visual_missing_picture': 'අතුරුදහන් වූ පින්තූරය',
      'visual_category_sorting': 'කාණ්ඩ අනුව වෙන් කිරීම',
      'shadow_match_demo': 'සෙවනැලි ගැලපීමේ ආදර්ශනය',
      'child_progress_suffix': 'ගේ ප්‍රගතිය',
      
      // Advanced Reports (TherapistStudentDetailScreen) additions
      'gt_label_success': 'මූලික සත්‍ය ලේබලය සාර්ථකව යවන ලදී!',
      'interaction_heatmaps': 'අන්තර්ක්‍රියාකාරී තාප සිතියම්',
      'no_interventions': 'තවමත් මැදිහත්වීම් ජනනය කර නැත.\nදරුවා තවත් ක්‍රීඩා කළ යුතුය.',
      'no_telemetry_data': 'මෙම සිසුවා සඳහා තවමත් ටෙලිමෙට්‍රි දත්ත නොමැත.',
      'no_touch_paths': 'ටෙලිමෙට්‍රි දත්තවල ස්පර්ශ මාර්ග හමු නොවීය.',
      'select_risk_label': 'අවදානම් ලේබලය තෝරන්න',
      'submit_gt_label': 'මූලික සත්‍ය ලේබලය ඉදිරිපත් කරන්න',
      'view_interaction_heatmaps': 'අන්තර්ක්‍රියාකාරී තාප සිතියම් බලන්න',
      'assessment_feeds_ml': 'ඔබගේ තක්සේරුව අපගේ යන්ත්‍ර ඉගෙනුම් ආකෘති පෝෂණය කරයි. කරුණාකර ඔවුන්ගේ දත්ත මත පදනම්ව මෙම සිසුවා සඳහා මූලික සත්‍ය අවදානම් මට්ටම තෝරන්න.',
      'cognitive_breakdown': 'සංජානන හැකියාවන්',
      'plan_tab': 'සැලැස්ම',
      'progress_tab': 'ප්‍රගතිය',
      'provide_clinical_label': 'සායනික ලේබලයක් ලබා දෙන්න',
      'recommended_interventions': 'නිර්දේශිත මැදිහත්වීම්',
      'sessions_tab': 'සැසි',
      'student_profile_title': 'සිසු ගිණුම',
      'weekly_progress': 'සතිපතා ප්‍රගතිය',
      
      'activity': 'ක්‍රියාකාරකම',
      'attempt': 'උත්සාහය',
      'attempts': 'උත්සාහයන්',
      'no_attempts_yet': 'තවමත් උත්සාහ කර නොමැත',
      'parent_label': 'මව්පියන්',
      'generating_report': 'වාර්තාව ජනනය කරමින්...',
      'download_clinical_report': 'සායනික වාර්තාව බාගන්න',
      'generating_assessment': 'තක්සේරුව ජනනය කරමින්...',
      'download_assessment_pdf': 'තක්සේරු PDF බාගන්න',
      'touch_precision_tracking': 'ස්පර්ශ නිරවද්‍යතා ලුහුබැඳීම',
      'strategy': 'ක්‍රමෝපාය',

      // Risk level display labels
      'risk_low': 'අඩු අවදානමක්',
      'risk_moderate': 'මධ්‍යස්ථ අවදානමක්',
      'risk_high': 'ඉහළ අවදානමක්',
      'risk_pending': 'දත්ත රැස් කිරීමේ දී...',

      // Cognitive index display names
      'visual_processing_score': 'දෘශ්‍ය සැකසීමේ වේගය',
      'phonological_awareness_score': 'ශබ්ද විද්‍යාත්මක දැනුවත්භාවය',
      'motor_precision_score': 'මෝටර් නිරවද්‍යතාව',
      'sustained_attention_score': 'ස්ථිර අවධානය',

      // Cognitive fallback (no data yet)
      'waiting_for_data': 'දත්ත රැස් කිරීමේ දී',
      'needs_more_play': 'තවත් ක්‍රීඩා අවශ්‍යයි',

      // No session data
      'no_sessions': 'සැසි දත්ත නොමැත.',
      
      'levels': 'මට්ටම්',
      'performance_trend': 'කාර්ය සාධන ප්‍රවණතාව',
      'accuracy_over_sessions': 'පසුගිය සැසි 7 තුළ නිරවද්‍යතාව',
      'time_spent': 'ගත කළ කාලය',
      'rounds_played': 'ක්‍රීඩා කළ වට ගණන',
      'score': 'ලකුණු',
      'time': 'කාලය',
      'no_data_available': 'මෙම කුසලතාව සඳහා දත්ත නොමැත.',
      'add_therapist': 'චිකිත්සකයෙකු එකතු කරන්න',
      'therapist_connections': 'චිකිත්සක සම්බන්ධතා',
      'manage_specialist_access': 'ඔබගේ දරුවාගේ දත්ත වෙත චිකිත්සක ප්‍රවේශය කළමනාකරණය කරන්න',
      'no_therapists_connected': 'චිකිත්සකයින් සම්බන්ධ කර නොමැත',
      'connect_reading_specialist': 'ඉගෙනුම් දත්ත සුරක්ෂිතව බෙදා ගැනීමට ඔබේ දරුවාගේ විශේෂඥයෙකු සමග සම්බන්ධ කරන්න.',
      'my_therapists': 'මගේ චිකිත්සකයින්',
      'pending_requests': 'පොරොත්තු ඉල්ලීම්',
      'find_therapists': 'චිකිත්සකයින් සොයන්න',
      'connect': 'සම්බන්ධ වන්න',
      'disconnect': 'විසන්ධි වන්න',
      'message': 'පණිවිඩයක් යවන්න',
      'no_connected_therapists': 'තවමත් සම්බන්ධිත චිකිත්සකයින් නොමැත.',
      'no_pending_requests': 'පොරොත්තු ඉල්ලීම් නොමැත.',
      'no_available_therapists': 'ලබාගත හැකි චිකිත්සකයින් හමු නොවීය.',
      'messaging_coming_soon': 'පණිවිඩ යැවීමේ විශේෂාංගය ළඟදීම!',
      'disconnect_therapist': 'චිකිත්සකයා විසන්ධි කරන්නද?',
      'disconnect_desc': 'ඔබට මෙම චිකිත්සකයාගෙන් විසන්ධි වීමට අවශ්‍ය බව නිසැකද? ',
      'disconnect_desc_full': 'මෙය ඔබගේ දරුවාගේ ඉගෙනුම් දත්ත වෙත ඇති ප්‍රවේශය අවලංගු කරනු ඇත. ඔබට පසුව නැවත සම්බන්ධ විය හැක.',
      'therapist_disconnected': 'චිකිත්සකයා විසන්ධි විය',
      'active': 'සක්‍රීය',

      'clinic': 'සායනය',
      'connected_child': 'සම්බන්ධිත දරුවා',
      'connected_since': 'සම්බන්ධ වූ දිනය',


      'all': 'සියල්ල',
      'system': 'පද්ධතිය',
      'therapist': 'චිකිත්සක',
      'no_notifications': 'තවමත් දැනුම්දීම් නොමැත.',
      'new': 'නව',
      'today': 'අද',
      'yesterday': 'ඊයේ',

      'activities_played': 'ක්‍රියාකාරකම්',
      'overall_accuracy': 'සමස්ත නිරවද්‍යතාව',
      'weekly_minutes': 'සතිපතා මිනිත්තු',
      'student_progress': 'සිසු ප්‍රගතිය',
      'withdraw_consent_info': 'ඔබට ඕනෑම වේලාවක දෙමාපිය ගිණුම් සැකසීම් හරහා\nඔබගේ කැමැත්ත ඉවත් කරගත හැක.',
      'dash_greeting_morning': 'සුබ උදෑසනක්, {name}!',
      'dash_greeting_afternoon': 'සුබ දහවලක්, {name}!',
      'dash_greeting_evening': 'සුබ සන්ධ්‍යාවක්, {name}!',
      'dash_greeting_night': 'සුබ රාත්‍රියක්, {name}!',
      'dash_streak_0': 'දින {streak} ක අඛණ්ඩ ගමනක්! 🔥',
      'dash_streak_low': 'දින {streak} ක අඛණ්ඩ ගමනක්! හොඳයි! 🔥',
      'dash_streak_high': 'දින {streak} ක අඛණ්ඩ ගමනක්! ගොඩක් හොඳයි! 🔥',
      'dash_learning_path': 'ඉගෙනුම් මාර්ගය 🧩',
      'dash_reading_practice': 'කියවීමේ පුහුණුව 📖',
      'dash_nav_home': 'මුල් පිටුව',
      'dash_nav_shop': 'සාප්පුව',
      'dash_nav_progress': 'ප්‍රගතිය',
      'dash_nav_parents': 'දෙමාපියන්',
      'change_photo': 'ඡායාරූපය වෙනස් කරන්න',
      'remove_photo': 'ඡායාරූපය ඉවත් කරන්න',
      'profile_photo': 'ගිණුමෙහි ඡායාරූපය',
      'scan_clinic_code': 'සායන කේතය පරිලෝකනය කරන්න',
      'connect_specialist_title': 'විශේෂඥයෙකු සම්බන්ධ කරන්න',
      'connect_specialist_desc': 'ඔබේ දරුවාගේ ගිණුම ඔවුන්ගේ චිකිත්සකයා හෝ විශේෂඥයා වෙත සම්බන්ධ කරන්න.',
      'clinic_code': 'සායන කේතය',
      'scan_qr_code': 'නැතහොත් QR කේතය ස්කෑන් කරන්න',
      'select_child': 'දරුවා තෝරන්න',
      'student': 'සිසුවා',
      'continue_to_consent': 'කැමැත්ත ලබා දීමට ඉදිරියට යන්න',
      'enter_valid_clinic_code': 'කරුණාකර නිවැරදි සායන කේතයක් ඇතුළත් කරන්න',
      'please_select_child': 'කරුණාකර දරුවෙකු තෝරන්න',
      'please_tap_checkbox': 'කරුණාකර එකඟ වීමට කොටුව මත තට්ටු කරන්න.',
      'successfully_connected': 'සාර්ථකව සම්බන්ධ විය!',
      'privacy_consent': 'පෞද්ගලිකත්ව කැමැත්ත',
      'what_you_are_sharing': 'ඔබ බෙදාගන්නා දේවල්:',
      'consent_bullet_1': 'ශබ්ද විද්‍යාත්මක දෝෂ රටා (උදා: b/d වැනි දෘශ්‍ය වැරදීම්)',
      'consent_bullet_2': 'ඉගෙනුම් ක්‍රියාකාරකම් සඳහා ගත කළ කාලය',
      'consent_bullet_3': 'සමස්ත කියවීමේ මට්ටමේ ප්‍රගතිය',
      'why_we_share_this': 'ඔබ මෙය බෙදා ගන්නේ ඇයි:',
      'why_we_share_desc': 'මෙය ඔබගේ දරුවාගේ විශේෂඥයාට ඔවුන්ගේ ප්‍රතිචාරය (RTI) තත්‍ය කාලීනව නිරීක්ෂණය කිරීමට ඉඩ සලසයි, එය චිකිත්සක සැසි සකස් කිරීමට උපකාරී වේ.',
      'consent_agree_text': 'සායන කේතය {clinicCode} සමඟ සම්බන්ධිත විශේෂඥයා සමඟ මගේ දරුවාගේ ඉගෙනුම් දත්ත බෙදා ගැනීමට මම කැමැත්තෙමි.',
      'connecting': 'සම්බන්ධ කරමින්...',
      'agree_connect': 'එකඟ වී සම්බන්ධ වන්න',
      
      // Therapist Profile Additions
      'therapist_account': 'චිකිත්සක ගිණුම',
      'clinic_connection': 'සායන සම්බන්ධතාවය',
      'scan_qr_code_therapist': 'මෙම QR කේතය දෙමාපියන්ට ස්කෑන් කිරීමට ලබා දෙන්න',
      'or_enter_code': 'හෝ කේතය ඇතුලත් කරන්න: ',
      'share_invite_code': 'කේතය බෙදාගන්න',
      'not_set': 'සකසා නැත',
      'contact_support': 'සහාය අමතන්න',
      'in_app_notifications': 'යෙදුම තුළ නිවේදන',
      'in_app_notifications_desc': 'යෙදුම තුළ වැදගත් දැනුම්දීම් ලබා ගන්න.',
      'update_clinic_name': 'සායනයේ නම යාවත්කාලීන කරන්න',
      'update_clinic_name_desc': 'ඔබගේ ගිණුමෙහි දිස්වීමට අවශ්‍ය සායනයේ නම ඇතුළත් කරන්න.',
      'clinic_name_updated': 'සායනයේ නම සාර්ථකව යාවත්කාලීන කරන ලදී!',
      'update_specialization': 'විශේෂඥතාව යාවත්කාලීන කරන්න',
      'update_specialization_desc': 'ඔබගේ ගිණුමෙහි දිස්වීමට අවශ්‍ය විශේෂඥතාව ඇතුළත් කරන්න.',
      'specialization_updated': 'විශේෂඥතාව සාර්ථකව යාවත්කාලීන කරන ලදී!',
      'share_invite_text': 'ආයුබෝවන්! සිප්සර හරහා ඔබ සමඟ සම්බන්ධ වීමට ලැබීම සතුටක්.\n\nකරුණාකර අපගේ ගිණුම් සම්බන්ධ කිරීම සඳහා මෙම ආරක්‍ෂිත සම්බන්ධතා කේතය [{clinicCode}] භාවිතා කරන්න. ඔබ යෙදුම ස්ථාපනය කර ඇත්නම්, දෙමාපියන්ගේ පිටුව හරහා කේතය ඇතුළත් කළ හැක.',
      'share_invite_subject': 'සිප්සර සම්බන්ධතා කේතය',
      'update_password_desc': 'පහතින් ඔබගේ නව මුරපදය ඇතුළත් කරන්න.',
      'current_password': 'වත්මන් මුරපදය',
      'new_password': 'නව මුරපදය',
      'delete_forever': 'සදහටම මකා දමන්න',
      'nav_students': 'සිසුන්',
      'nav_profile': 'ගිණුම',
      'moko_greeting': 'ආයුබෝවන්! මම මොකෝ!\nඔබව හමුවීම ගැන මට ගොඩක් සතුටුයි!',
      'intro_page1_title': 'ආයුබෝවන්! මම මොකෝ!\nමම තමයි ඔබේ දරුවාගේ අලුත් ඉගෙනුම් මිතුරා!',
      'intro_page2_title': 'විනෝදජනක ක්‍රීඩා මගින් සිංහල ඉගෙනීමට සිප්සර ඔබට උදව් කරනවා!',
      'intro_page3_title': 'ඔබට ඔවුන්ගේ ප්‍රගතිය නිරීක්ෂණය කර පහසුවෙන් විශේෂඥයින් සම්බන්ධ කරගන්න පුළුවන්!',
      'continue_btn': 'ඉදිරියට යන්න',
      'get_started_btn': 'ආරම්භ කරන්න',
    },
    'en': {
      'welcome_title': 'Welcome!',
      'welcome_subtitle': 'your sinhala learning\nadventure awaits!',
      'welcome_btn_signup': 'get started',
      'welcome_btn_signin': 'i already have an account',
      'btn_signin': 'sign in',
      'signing_in': 'signing in...',
      'btn_signup': 'sign up',
      'email': 'email',
      'email_hint': 'your email address',
      'password': 'password',
      'password_hint': 'your password',
      'password_hint_create': 'create password',
      'forgot_password': 'forgot password?',
      'forgot_password_desc': 'Don\'t worry! It happens. Please enter the email address associated with your account.',
      'sending_code': 'sending code...',
      'send_code': 'send code',
      'check_email': 'Check your email',
      'otp_sent_to': 'We\'ve sent a code to\n',
      'otp_enter_below': '\n\nPlease enter the code below to verify.',
      'resend_code_in': 'Resend code in {time}',
      'resend_otp_now': 'Resend code now',
      'verify_code': 'Verify Code',
      'dont_have_account': 'don\'t have an account? ',
      'already_have_account': 'already have an account? ',
      'signin_title': 'welcome back!',
      'signin_subtitle': 'sign in to continue your adventure',
      'signup_title': 'create your account',
      'signup_subtitle': 'join the learning adventure today',
      'parent_name': 'Parent\'s Name',
      'parent_name_hint': 'your name',
      'role_parent': 'parent',
      'role_therapist': 'therapist',
      'specialization_hint': 'specialization (e.g. speech therapist)',
      'clinic_hint': 'clinic name (optional)',
      'or': 'or',
      'mobile_number': 'mobile number',
      'mobile_number_hint': 'Your mobile number',
      'confirm_password': 'Confirm Password',
      'confirm_password_hint': 'Re-enter your password',
      'agree_terms': 'I agree to Sipsara\'s Terms of Use and Privacy Policy.',
      'benefit_private': 'private',
      'start_assessment': 'start assessment',
      'maybe_later': 'maybe later',
      'assessment_later_desc': 'you can always start this from the student\'s profile.',
      'start_from_profile': 'you can always start this from the student\'s profile.',
      'language': 'Language',
      'select_language': 'Select Language',
      'settings': 'Settings',
      'field_required': 'This field is required',
      'invalid_email': 'Please enter a valid email address',
      'invalid_phone': 'Please enter a valid phone number',
      'password_short': 'Password must be at least 6 characters long',
      'passwords_dont_match': 'Passwords do not match',
      'must_agree_terms': 'You must agree to the Terms of Use and Privacy Policy',
      'or_continue_with': 'Or continue with',
      'error_occurred': 'An error occurred. Please try again.',
      'change': 'change',
      'parent_account': 'parent account',
      'account_security': 'account & security',
      'full_name': 'full name',
      'delete_account': 'delete account',
      'my_students': 'my students',
      'subscription': 'subscription',
      'coming_soon': 'coming soon',
      'notifications': 'notifications',
      'help_support': 'help & support',
      'edit': 'edit',
      'parent_hub': 'parent hub',
      'hello_parent': 'hello',
      'children': 'children',
      'this_week': 'this week',
      'connected': 'connected',
      'reports': 'reports',
      'messages': 'messages',
      'therapists': 'therapists',
      'your_children': 'your children',
      'select_a_child': 'Select a Child',
      'recent_activity': 'recent activity',
      'last_played': 'last played',
      'skills_mastered': 'skills mastered',
      'student_added': 'student added!',
      'student_setup_ready_1': ' is all set up and ready to learn.',
      'personalize_learning': 'personalize learning',
      'evaluation_desc_1': 'a quick 2-minute evaluation will help us understand ',
      'evaluation_desc_2': '\'s unique learning style and tailor activities specifically for them.',
      'personalized': 'personalized',
      '2_min': '2 mins',
      'private': 'private',
      'assessment_prompt_desc': 'a quick 2-minute assessment helps us understand their unique learning style and tailor activities specifically for them.',
      'add_student': 'add student',
      'pending': 'Pending',
      'completed': 'Completed',
      'premium_coming_soon': 'premium plans coming soon!',
      'premium_desc': "we're crafting amazing premium features to supercharge your child's learning journey.",
      'login_alerts': 'login alerts',
      'login_alerts_desc': 'get notified when your account is accessed from a new device.',
      'learning_progress': 'learning progress',
      'learning_progress_desc': 'get notified when your child completes a screening or milestone.',
      'app_updates': 'app updates & features',
      'app_updates_desc': 'receive important announcements about new educational tools.',
      'email_support': 'email support',
      'phone_support': 'phone support',
      'faq': 'FAQ',
      'logout': 'logout',
      'activities': 'activities',
      'accuracy': 'accuracy',
      'day_streak': 'day streak',
      'stars_earned': 'stars earned',
      'weekly_activity': 'weekly activity',
      'recent_skills': 'recent skills',
      'view_advanced_reports': 'View Advanced Reports & Heatmap',
      'progress_report': 'progress report',
      'no_activities_played': 'No activities played yet',
      'whos_learning_today': 'who\'s learning today?',
      'ready': 'Ready',

      // Parent Hub Additions
      'last_active_prefix': 'last active: ',
      'view_progress_btn': 'view progress →',
      'never': 'never',
      'recent': 'recent',
      'add_student_first_msg': 'add a student first to view progress',
      'add_student_settings_hint': 'go to settings to add your first student',

      'delete_account_desc': 'This action is irreversible. All your data and student profiles will be permanently deleted.',
      'delete_account_confirm': 'To confirm, type your full name:',
      'cancel': 'Cancel',
      'password_changed': 'Password changed!',
      'update_password': 'Update Password',
      'update_name': 'Update Name',
      'update_name_desc': 'Enter your full name to update your profile.',
      'save_changes': 'Save Changes',
      'name_updated_success': 'Name updated successfully!',
      'update_email_title': 'Update Email',
      'update_email_desc': 'Enter a new email address. We will send a verification code to confirm.',
      'send_verification_code': 'Send Verification Code',
      'verify_email': 'Verify Email',
      'verify_email_desc': 'We sent a 6-digit verification code to ',

      'verify_and_update': 'Verify & Update',
      'email_updated_success': 'Email updated successfully!',
      'change_password_title': 'Change Password',
      'change_password_desc': 'Protect your account with a strong new password.',
      'delete': 'Delete',
      'delete_permanently': 'Delete Permanently',
      'reset_skills_title': 'Reset skills?',
      'reset_skills_desc_prefix': 'Are you sure you want to reset all skill progress for ',
      'reset_skills_desc_suffix': '? Completed activities, scores, and unlock status will be reset back to the start.',
      'reset_skills_success': ' skills progress reset!',
      'reset_skills_btn': 'Reset skills',
      'delete_student_title': 'Delete student?',
      'delete_student_desc_prefix': 'Are you absolutely sure you want to delete ',
      'delete_student_desc_suffix': '? This action cannot be undone and all learning progress will be lost permanently.',
      'delete_student_therapist_warning': 'This student is connected to a therapist. Deleting them will permanently break that connection.',
      'delete_student_success': ' deleted successfully.',

      'add_student_subtitle': 'add a student to get started',
      'assessment_profile': 'Assessment Profile',
      'select_area_evaluate': 'Select an area to evaluate.',
      'cat_basic': 'Basic Dyslexia Evaluation',
      'cat_reading': 'Reading & Visual Perception',
      'cat_writing': 'Writing Difficulties',
      'cat_other': 'Other Associated Difficulties',
      'btn_yes': 'Yes',
      'btn_no': 'No',
      'question_prefix': 'Question ',
      'btn_next_question': 'Next Question',
      'btn_finish_evaluation': 'Finish Evaluation',

      // Add/Edit Student
      'add_student_desc': 'add an additional student for free. you are allowed to add up to 5 children to your account.',
      'choose_avatar': 'choose a character profile picture',
      'fantasy': 'Fantasy',
      'kids': 'Kids',
      'student_first_name_hint': 'student first name',
      'student_last_name_hint': 'student last name',
      'required_field': 'required',
      'grade_1': 'Grade 1',
      'auto_set': 'auto-set',
      'daily_limit_prefix': 'daily limit: ',
      'student_updated_success': 'student updated successfully!',
      'grade_set_info': 'grade is set to Grade 1',

      'update_changes': 'update changes',
      'edit_student': 'edit student',
      'no_limit': 'No Limit',
      'minutes': 'minutes',
      'hours': 'hours',
      'hour': 'hour',

      // Consent Screen
      'parental_consent': 'parental consent',
      'student_protection_agreement': 'student protection agreement',
      'consent_review_terms': 'please review and accept the following terms before proceeding.',
      'consent_items': 'consent items',
      'guardian_confirmation_title': 'guardian confirmation',
      'guardian_confirmation_desc': 'I confirm that I am the parent or legal guardian of this child and have the authority to provide consent on their behalf.',
      'data_collection_title': 'learning data collection',
      'data_collection_desc': 'I consent to the collection and processing of my child\'s learning data (responses, progress, and performance) to personalize their educational experience.',
      'screening_purpose_title': 'dyslexia screening purpose',
      'screening_purpose_desc': 'I understand that this app is designed for Grade 1 dyslexia screening and learning support. It does not provide medical diagnoses and should be used alongside professional guidance.',
      'terms_privacy_title': 'terms of use & privacy policy',
      'terms_privacy_desc': 'I have read and agree to the terms of use and privacy policy. I understand my child\'s data will be stored securely and will not be shared with third parties.',
      'digital_signature': 'digital signature',
      'digital_signature_desc': 'Type your full name below as your digital signature.',
      'signature_hint': 'Parent / Guardian Full Name',
      'date_prefix': 'Date: ',
      'agree_continue': 'I Agree & Continue',
      
      // New Parent Hub Inner Screens Additions
      'skill_analytics': 'Skill Analytics',
      'phonological_awareness': 'Phonological Awareness',
      'visual_discrimination': 'Visual Discrimination',
      'memory': 'Memory',
      'letter_knowledge': 'Letter Knowledge',
      'tracing': 'Tracing',
      'visual_hidden_search': 'Hidden Search',
      'visual_pattern_adventure': 'Pattern Adventure',
      'visual_sorting_adventure': 'Sorting Adventure',
      'visual_odd_one_out': 'Odd One Out',
      'visual_memory_hats': 'Memory Hats',
      'visual_picture_matching': 'Picture Matching',
      'visual_connect_pairs': 'Connect Pairs',
      'visual_shadow_matching': 'Shadow Matching',
      'visual_tangled_paths': 'Tangled Paths',
      'visual_position_concepts': 'Position Concepts',
      'visual_missing_picture': 'Missing Picture',
      'visual_category_sorting': 'Category Sorting',
      'shadow_match_demo': 'Shadow Match Demo',
      'child_progress_suffix': '\'s progress',
      
      // Advanced Reports (TherapistStudentDetailScreen) additions
      'gt_label_success': 'Ground Truth Label submitted successfully!',
      'interaction_heatmaps': 'Interaction Heatmaps',
      'no_interventions': 'No interventions generated yet.\nChild needs to play more games.',
      'no_telemetry_data': 'No telemetry data available for this student yet.',
      'no_touch_paths': 'No touch paths found in the telemetry data.',
      'select_risk_label': 'Select Risk Label',
      'submit_gt_label': 'Submit Ground Truth Label',
      'view_interaction_heatmaps': 'View Interaction Heatmaps',
      'assessment_feeds_ml': 'Your assessment feeds our ML models. Please select the ground-truth risk level for this student based on their data.',
      'cognitive_breakdown': 'cognitive breakdown',
      'plan_tab': 'plan',
      'progress_tab': 'progress',
      'provide_clinical_label': 'provide clinical label',
      'recommended_interventions': 'recommended interventions',
      'sessions_tab': 'sessions',
      'student_profile_title': 'student profile',
      'weekly_progress': 'weekly progress',
      
      'activity': 'Activity',
      'attempt': 'Attempt',
      'attempts': 'Attempts',
      'no_attempts_yet': 'No Attempts Yet',
      'parent_label': 'parent',
      'generating_report': 'Generating Report...',
      'download_clinical_report': 'Download Clinical Report',
      'generating_assessment': 'Generating Assessment...',
      'download_assessment_pdf': 'Download Assessment PDF',
      'touch_precision_tracking': 'Aggregated touch precision tracking',
      'strategy': 'Strategy',

      // Risk level display labels
      'risk_low': 'Low Risk',
      'risk_moderate': 'Moderate Risk',
      'risk_high': 'Needs Attention',
      'risk_pending': 'Collecting Data...',

      // Cognitive index display names
      'visual_processing_score': 'Visual Processing Speed',
      'phonological_awareness_score': 'Phonological Awareness',
      'motor_precision_score': 'Motor Precision',
      'sustained_attention_score': 'Sustained Attention',

      // Cognitive fallback (no data yet)
      'waiting_for_data': 'Waiting for Data',
      'needs_more_play': 'Needs More Play',

      // No session data
      'no_sessions': 'No session data available.',

      'levels': 'Levels',
      'performance_trend': 'Performance Trend',
      'accuracy_over_sessions': 'accuracy over last 7 sessions',
      'time_spent': 'Time Spent',
      'rounds_played': 'Rounds Played',
      'score': 'Score',
      'time': 'Time',
      'no_data_available': 'No data available for this skill.',
      'add_therapist': 'Add Therapist',
      'therapist_connections': 'Therapist Connections',
      'manage_specialist_access': 'Manage specialist access to your child\'s data',
      'no_therapists_connected': 'No therapists connected',
      'connect_reading_specialist': 'Connect your child\'s reading specialist or speech-language pathologist to share learning data securely.',
      'my_therapists': 'My Therapists',
      'pending_requests': 'Pending Requests',
      'find_therapists': 'Find Therapists',
      'connect': 'Connect',
      'disconnect': 'Disconnect',
      'message': 'Message',
      'no_connected_therapists': 'No connected therapists yet.',
      'no_pending_requests': 'No pending requests.',
      'no_available_therapists': 'No available therapists found.',
      'messaging_coming_soon': 'Messaging feature coming soon!',
      'disconnect_therapist': 'Disconnect therapist?',
      'disconnect_desc': 'Are you sure you want to disconnect from ',
      'disconnect_desc_full': 'This will revoke access to learning data. You can reconnect later.',
      'therapist_disconnected': 'Therapist disconnected',
      'active': 'Active',

      'clinic': 'Clinic',
      'connected_child': 'Connected Child',
      'connected_since': 'Connected Since',


      'all': 'All',
      'system': 'System',
      'therapist': 'Therapist',
      'no_notifications': 'No notifications yet.',
      'new': 'new',
      'today': 'Today',
      'yesterday': 'Yesterday',

      'activities_played': 'Activities Played',
      'overall_accuracy': 'Overall Accuracy',
      'weekly_minutes': 'Weekly Minutes',
      'student_progress': 'Student Progress',
      'withdraw_consent_info': 'you can withdraw consent at any time\nfrom the parent account settings.',
      'dash_greeting_morning': 'Good morning, {name}!',
      'dash_greeting_afternoon': 'Good afternoon, {name}!',
      'dash_greeting_evening': 'Good evening, {name}!',
      'dash_greeting_night': 'Good night, {name}!',
      'dash_streak_0': '{streak} day streak! 🔥',
      'dash_streak_low': '{streak} day streak! Good! 🔥',
      'dash_streak_high': '{streak} day streak! Very good! 🔥',
      'dash_learning_path': 'Learning Path 🧩',
      'dash_reading_practice': 'Reading Practice 📖',
      'dash_nav_home': 'home',
      'dash_nav_shop': 'shop',
      'dash_nav_progress': 'progress',
      'dash_nav_parents': 'parents',
      'change_photo': 'Change Photo',
      'remove_photo': 'Remove Photo',
      'profile_photo': 'Profile Photo',
      'scan_clinic_code': 'scan clinic code',
      'connect_specialist_title': 'connect specialist',
      'connect_specialist_desc': 'link your child\'s account to their therapist or reading specialist.',
      'clinic_code': 'clinic code',
      'scan_qr_code': 'or scan QR code',
      'select_child': 'select child',
      'student': 'student',
      'continue_to_consent': 'continue to consent',
      'enter_valid_clinic_code': 'please enter a valid 6-digit clinic code',
      'please_select_child': 'please select a child',
      'please_tap_checkbox': 'please tap the checkbox to agree.',
      'successfully_connected': 'successfully connected!',
      'privacy_consent': 'privacy consent',
      'what_you_are_sharing': 'what you are sharing:',
      'consent_bullet_1': 'phonetic error patterns (e.g., visual reversals like b/d)',
      'consent_bullet_2': 'time spent on learning activities',
      'consent_bullet_3': 'overall reading level progression',
      'why_we_share_this': 'why we share this:',
      'why_we_share_desc': 'this allows your child\'s specialist to track their response to intervention (RTI) in real-time, helping them adjust therapy sessions.',
      'consent_agree_text': 'i consent to sharing my child\'s learning data with the specialist associated with clinic code {clinicCode}.',
      'connecting': 'connecting...',
      'agree_connect': 'agree & connect',
      
      // Therapist Profile Additions
      'therapist_account': 'therapist account',
      'clinic_connection': 'clinic connection',
      'scan_qr_code_therapist': 'Have parents scan this QR code',
      'or_enter_code': 'or enter code: ',
      'share_invite_code': 'share invite code',
      'not_set': 'not set',
      'contact_support': 'contact support',
      'in_app_notifications': 'in-app notifications',
      'in_app_notifications_desc': 'receive important alerts within the app.',
      'update_clinic_name': 'Update Clinic Name',
      'update_clinic_name_desc': 'Enter the clinic name to display on your profile.',
      'clinic_name_updated': 'Clinic name updated successfully!',
      'update_specialization': 'Update Specialization',
      'update_specialization_desc': 'Enter your specialization to display on your profile.',
      'specialization_updated': 'Specialization updated successfully!',
      'share_invite_text': 'Hello! I am excited to work with you on Sipsara.\n\nPlease use my secure connection code [{clinicCode}] to link our accounts. If you have the app installed, you can enter the code in the Parent Hub.',
      'share_invite_subject': 'Sipsara Connection Code',
      'update_password_desc': 'Enter your new password below.',
      'current_password': 'Current Password',
      'new_password': 'New Password',
      'delete_forever': 'Delete Forever',
      'nav_students': 'Students',
      'nav_profile': 'Profile',
      'moko_greeting': "Hi there! I'm Moko!\nI'm so excited to meet you!",
      'intro_page1_title': "Hi! I'm Moko!\nI'll be your child's new learning buddy!",
      'intro_page2_title': 'Sipsara makes learning Sinhala fun with adaptive games!',
      'intro_page3_title': 'You can easily track their progress and connect with therapists!',
      'continue_btn': 'continue',
      'get_started_btn': 'get started',
    }
  };
}
